# Generated by Django 3.2.9 on 2021-12-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal_app', '0005_userpage_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='followers',
            field=models.ManyToManyField(related_name='followers', to='jornal_app.User'),
        ),
        migrations.AlterField(
            model_name='following',
            name='following',
            field=models.ManyToManyField(related_name='following', to='jornal_app.User'),
        ),
        migrations.AlterField(
            model_name='friendlist',
            name='blooking_users',
            field=models.ManyToManyField(related_name='black_list', to='jornal_app.User'),
        ),
        migrations.AlterField(
            model_name='friendlist',
            name='friends',
            field=models.ManyToManyField(related_name='friends', to='jornal_app.User'),
        ),
    ]
