# Generated by Django 3.2.9 on 2021-12-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal_app', '0006_auto_20211215_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='following',
            name='following_pages',
            field=models.ManyToManyField(related_name='following_pages', to='jornal_app.User'),
        ),
    ]
