# Generated by Django 3.2.9 on 2021-12-15 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jornal_app', '0007_following_following_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='following_pages',
        ),
    ]
