# Generated by Django 3.2.9 on 2021-12-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal_app', '0010_auto_20211216_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageuserpermission',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('EDITOR', 'EDITOR'), ('AUTHOR', 'AUTHOR')], max_length=50),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('EDITOR', 'EDITOR'), ('AUTHOR', 'AUTHOR')], max_length=50),
        ),
    ]
