# Generated by Django 4.0 on 2021-12-16 17:20

import django.core.validators
from django.db import migrations, models
import server.jornal_app.models.abstracts


class Migration(migrations.Migration):

    dependencies = [
        ('jornal_app', '0011_auto_20211216_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=server.jornal_app.models.abstracts.save_media_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['JPEG', 'JPG', 'PNG', 'GIF', 'TIFF', 'PSD', 'PDF', 'EPS', 'AI', 'INDD', 'RAW', 'MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=server.jornal_app.models.abstracts.save_media_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['JPEG', 'JPG', 'PNG', 'GIF', 'TIFF', 'PSD', 'PDF', 'EPS', 'AI', 'INDD', 'RAW', 'MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AddField(
            model_name='reply',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=server.jornal_app.models.abstracts.save_media_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['JPEG', 'JPG', 'PNG', 'GIF', 'TIFF', 'PSD', 'PDF', 'EPS', 'AI', 'INDD', 'RAW', 'MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
