# Generated by Django 4.0 on 2021-12-18 14:08

from django.db import migrations, models
import server.jornal_app.models.abstracts


class Migration(migrations.Migration):

    dependencies = [
        ('jornal_app', '0012_comment_media_post_media_reply_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=server.jornal_app.models.abstracts.save_media_file_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=server.jornal_app.models.abstracts.save_media_file_path),
        ),
        migrations.AlterField(
            model_name='reply',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=server.jornal_app.models.abstracts.save_media_file_path),
        ),
    ]
