# Generated by Django 4.0 on 2021-12-19 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jornal_app', '0014_room_delete_othermessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='friend',
            new_name='receiver',
        ),
    ]
