# Generated by Django 4.0 on 2021-12-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jornal_app', '0015_rename_friend_room_receiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='author',
            new_name='sender',
        ),
    ]
