# Generated by Django 4.0.1 on 2022-02-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal_app', '0020_alter_user_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='language',
            field=models.JSONField(default='en-us'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='look_account',
            field=models.BooleanField(default=False),
        ),
    ]
