# Generated by Django 4.0.1 on 2022-02-21 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jornal_app', '0023_alter_usersettings_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('posts', models.ManyToManyField(related_name='saved_posts', to='jornal_app.Post')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_saved_posts', to='jornal_app.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
